SDS Scripts/MigrateCleverData.ps1
=> MigrateCleverData script: Changing naming convention from Archived to Retired

SDSProfileManagementDocs/api/synchronizationProfile_create.md, SDSProfileManagementDocs/api/synchronizationProfile_get_errors.md, SDSProfileManagementDocs/api/synchronizationProfile_post_start.md, SDSProfileManagementDocs/api/synchronizationProfile_update.md, SDSProfileManagementDocs/resources/domain.md, SDSProfileManagementDocs/resources/synchronizationCustomization.md, SDSProfileManagementDocs/resources/synchronizationProfile.md, SDSProfileManagementDocs/resources/synchronizationStatus.md, SDSProfileManagementDocs/resources/verificationMessage.md, SDSProfileManagementDocs/scenarios/SDSCreateProfile.md, SDSProfileManagementDocs/scenarios/SDSCreateProfileAPI.md, SDSProfileManagementDocs/scenarios/SDSProfileAPIIntroduction.md, SDSProfileManagementDocs/scenarios/TroubleshootingSyncFailures.md, SDSProfileManagementDocs/scenarios/UpdateSyncProfiles.md
Update for api changes, fix links and models
=> Update documentation for SDS APIs

EDUGraphAPIs/Rostering/resources/educationclass.md, EDUGraphAPIs/Rostering/resources/educationorganization.md, EDUGraphAPIs/Rostering/resources/educationroot.md, EDUGraphAPIs/Rostering/resources/educationschool.md, EDUGraphAPIs/Rostering/resources/educationstudent.md, EDUGraphAPIs/Rostering/resources/educationteacher.md, EDUGraphAPIs/Rostering/resources/educationterm.md, EDUGraphAPIs/Rostering/resources/educationuser.md
Various changes to the resource entries after reviewing.
=> Reviewed resources.

SDSProfileManagementDocs/api/synchronizationProfile_create.md, SDSProfileManagementDocs/api/synchronizationProfile_delete.md, SDSProfileManagementDocs/api/synchronizationProfile_get.md, SDSProfileManagementDocs/api/synchronizationProfile_get_errors.md, SDSProfileManagementDocs/api/synchronizationProfile_get_status.md, SDSProfileManagementDocs/api/synchronizationProfile_get_uploadurl.md, SDSProfileManagementDocs/api/synchronizationProfile_list.md, SDSProfileManagementDocs/api/synchronizationProfile_post_pause.md, SDSProfileManagementDocs/api/synchronizationProfile_post_reset.md, SDSProfileManagementDocs/api/synchronizationProfile_post_resume.md, SDSProfileManagementDocs/api/synchronizationProfile_post_start.md, SDSProfileManagementDocs/api/synchronizationProfile_update.md, SDSProfileManagementDocs/scenarios/TroubleshootingSyncFailures.md
update version from testsds to testeduapi
=> update version from testsds to testeduapi

SDSProfileManagementDocs/resources/oneRosterApiDataProvider.md
fix oneRosterApiDataProvider strings
=> fix oneRosterApiDataProvider strings

SDSProfileManagementDocs/api/synchronizationProfile_create.md, SDSProfileManagementDocs/api/synchronizationProfile_delete.md, SDSProfileManagementDocs/api/synchronizationProfile_get.md, SDSProfileManagementDocs/api/synchronizationProfile_get_errors.md, SDSProfileManagementDocs/api/synchronizationProfile_get_status.md, SDSProfileManagementDocs/api/synchronizationProfile_get_uploadurl.md, SDSProfileManagementDocs/api/synchronizationProfile_list.md, SDSProfileManagementDocs/api/synchronizationProfile_post_pause.md, SDSProfileManagementDocs/api/synchronizationProfile_post_reset.md, SDSProfileManagementDocs/api/synchronizationProfile_post_resume.md, SDSProfileManagementDocs/api/synchronizationProfile_post_start.md, SDSProfileManagementDocs/api/synchronizationProfile_update.md, SDSProfileManagementDocs/resources/fileSynchronizationVerificationMessage.md, SDSProfileManagementDocs/resources/synchronizationError.md, SDSProfileManagementDocs/resources/synchronizationProfile.md, SDSProfileManagementDocs/scenarios/SDSCreateProfile.md, SDSProfileManagementDocs/scenarios/SDSCreateProfileAPI.md, SDSProfileManagementDocs/scenarios/TroubleshootingSyncFailures.md
- Update graph version
- Fix links
- fix upload steps
- document profile creation monitoring
=> Updates for SDS APIs

SDSProfileManagementDocs/api/educationsynchronizationprofile_uploadurl.md, SDSProfileManagementDocs/resources/educationcsvdataprovider.md, SDSProfileManagementDocs/resources/educationfilesynchronizationverificationmessage.md, SDSProfileManagementDocs/resources/educationidentitycreationconfiguration.md, SDSProfileManagementDocs/resources/educationidentitydomain.md, SDSProfileManagementDocs/resources/educationidentitymatchingconfiguration.md, SDSProfileManagementDocs/resources/educationidentitymatchingoptions.md, SDSProfileManagementDocs/resources/educationonerosterapidataprovider.md, SDSProfileManagementDocs/resources/educationpowerschooldataprovider.md, SDSProfileManagementDocs/resources/educationsynchronizationcustomization.md, SDSProfileManagementDocs/resources/educationsynchronizationcustomizations.md, SDSProfileManagementDocs/resources/educationsynchronizationerror.md, SDSProfileManagementDocs/resources/educationsynchronizationlicenseassignment.md, SDSProfileManagementDocs/resources/educationsynchronizationprofile.md, SDSProfileManagementDocs/resources/educationsynchronizationprofilestatus.md
Resources - Updated JSON syntax blocks and added HTML tagging for AppVeyor
=> Johnau edit

SDSProfileManagementDocs/resources/educationSynchronizationConnectionSettings.md, SDSProfileManagementDocs/resources/educationSynchronizationOAuth1ConnectionSettings.md, SDSProfileManagementDocs/resources/educationSynchronizationOAuth2ClientCredentialsConnectionSettings.md, SDSProfileManagementDocs/resources/educationonerosterapidataprovider.md
Add new resources and properties for OneRoster provider
=> Add new resources and properties for OneRoster provider

OneRosterTools/PostmanCollection/OneRoster V1.1-OAuth1a.postman_collection.json, OneRosterTools/PostmanCollection/OneRoster V1.1-OAuth2.postman_collection.json, OneRosterTools/PostmanCollection/OneRoster-CredentialsTemplate.postman_environment.json, OneRosterTools/PostmanCollection/readme.md
Add directory for OneRoster tools and Postman collection
=> Add Postman collection for OneRoster v1.1 APIs required by SDS

SDSProfileManagementDocs/README.md
It looks like some filenames changed, but links were not updated.
=> Fixed broken links.

Teams Scripts/Add-GroupOwners-To-Teams.ps1, Teams Scripts/Sync-GroupMembership-To-Team.ps1
Identify and explicitly log license issues.
Improve and clarify logging.
Standardize code for Add-TeamUser.
Theoretical fix for authentication expiration issues.
=> Improvements to Teams Sync Scripts

Teams Scripts/Add-GroupOwners-To-Teams.ps1
Adds -isArchived to the $select statement used to query beta/teams/{groupId} endpoint to confirm Team existence.
Default to excluding teams where -isArchived is not $false
Add -includeArchived switch; include groups where -isArchived -ne $false if set.
=> By default, exclude archived Teams. Introduce -includeArchived switch

OneRosterTools/PostmanCollection/OneRoster V1.1-OAuth2.postman_collection.json, OneRosterTools/PostmanCollection/OneRoster-CredentialsTemplate.postman_environment.json
This reverts commit b320c287ed4fb2e2b286e1d21332c80205c5648a.
=> Revert "Revert "Updating with Latest Postman Collection for OAuth2""

SDS Scripts/Create-SDS_Information_Barriers.ps1, SDS Scripts/Get-All_SDS_Attributes.ps1, SDS Scripts/Rename-Expired_Classes.ps1, SDS Scripts/Update-AnchorID_Attributes.ps1
Adding script to create information barriers from SDS created administrative units for each school and All Teachers security group.  Also few bug fixes.
=> Automate creation of Information Barriers based on Tenant AU topology

SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
Making changes to implement Graph API.
=> Modified Export-Class_Membership_for_Restrictions.ps1 script to use Graph API

SDS Scripts/Get-SectionUsageReport.ps1
_132838_  
_The script will query all SDS created sections and write their properties to a file_
_The ADAL cmdlets in used in the SDS PowerShell scripts in the O365 repo do not work. We need to replace all of the ADAL cmdlets with ones using another module (MSGraph with common.ps1 or AzureAD is preferred if possible)_
- Import file 'common.ps1' with common functions to the directory alongside the executing script
- Create output folder if it does not exist
- Write messages to log file and console
- Main function to get all Sections of Edu Object Type Section
_This script will use the Graph to pull the section usage report and output them to a csv. A folder will be created in the same directory as the script itself and contains a log file and the csv_
_NA_
.\Get-SectionUsageReport.ps1
=> - updated Get-SectionUsageReport scirpt using graphAPI

SDS Scripts/Get-InformationBarrierSegmentsForUsers.ps1, SDS Scripts/Get-User_Information_Barrier_Segments.ps1
Added script to pull information barrier policies and segments for users
=> Get Information Barrier Segments for Users

SDS Scripts/Get-All_Sections_and_Memberships.ps1
Making changes to Get-All_Sections_and _Memberships.ps1 to have ExchangeOnlineManagement
[_Please put the related issue number to reference if applicable_  ](https://dev.azure.com/1edu/DIP%20Master/_workitems/edit/132835)
Modified to have ExchangeOnlineManagement module
_Why is this change being proposed?_
- change 1
- change 2
- change N
_Detailed description of the change(s)_
_Any additional information or context_
[Example](www.microsoft.com)
=> Making changes to Get-All_Sections_and _Memberships.ps1 to have ExchangeOnlineManagement

SDS Scripts/Email Restrictions/Set-Acceptance_Permissions_All_Admins.ps1
Changes made to convert mailbox permissions from MSOL functions to use Graph and EXO.
=> Convert MSOL functions to Graph and EXO

SDS Scripts/Get-User_Information_Barrier_Segments.ps1
internal 143663
Replaced get-recipient cmdlet with get-user
Get-User_Information_Barrier_Segments.ps1 does not seem to work for users without an exchange email. 
see above
_Detailed description of the change(s)_
_Any additional information or context_
[Example](www.microsoft.com)
=> Changes needed to replace get-recipient with get-user

SDS Scripts/Get-User_Information_Barrier_Segments.ps1
_Please put the related issue number to reference if applicable_  
Changes for get-user to return all instead of 1st 1k and avoid memory issues
Get-User only returns 1000 records by defualt
-Force unlimited result size
-Only return users with information barrier segments
-Make changes to cut down on memory consumption
_Detailed description of the change(s)_
_Any additional information or context_
[Example](www.microsoft.com)
=> Changes for get-user to return all instead of 1st 1k avoid memory issues

SDS Scripts/Remove-SchoolAU_Memberships.ps1, SDS Scripts/Remove-SchoolSG_Memberships.ps1
internal 122055
Added no memberships check and return with message.  Also corrected page filename
No memberships will error and continue the script.
=> Added no memberships check and return with message

CustomSolutions/Create-non_SDS_Information_Barriers.ps1, SDS Scripts/Create-SDS_Information_Barriers.ps1, SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1, SDS Scripts/Email Restrictions/Set-Acceptance_Permissions_All_Admins.ps1, SDS Scripts/Email Restrictions/Set-Acceptance_Permissions_All_Students.ps1, SDS Scripts/Email Restrictions/Set-Acceptance_Permissions_All_Teachers.ps1, SDS Scripts/Email Restrictions/Set-Acceptance_Permissions_SDS_Sections.ps1, SDS Scripts/Email Restrictions/Set-Acceptance_Permissions_Students_by_Grade.ps1, SDS Scripts/Get-All_SDS_Attributes.ps1, SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1, SDS Scripts/Get-All_SDS_Troubleshooting_Attributes.ps1, SDS Scripts/Get-All_Schools_and_Memberships.ps1, SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1, SDS Scripts/Get-All_Students_and_Teachers.ps1, SDS Scripts/Get-SectionUsageReport.ps1, SDS Scripts/License Scripts/Add-Intune_Licenses.ps1, SDS Scripts/License Scripts/Remove-Intune_Licenses.ps1, SDS Scripts/MigrateClassGroupsToTeams.ps1, SDS Scripts/Remove-All_Schools.ps1, SDS Scripts/Remove-All_Section_Memberships.ps1, SDS Scripts/Remove-SchoolAU_Memberships.ps1, SDS Scripts/Remove-SchoolSG_Memberships.ps1, SDS Scripts/Rename-Expired_Classes.ps1, SDS Scripts/Restore-V1_AnchorID_Attributes.ps1, SDS Scripts/Set-SDS_Attributes_For_Administrative_Units.ps1, SDS Scripts/Unrename-Expired_Classes.ps1, SDS Scripts/Update-AnchorID_Attributes.ps1
internal 122056
Added output on where to check logs after script completes
Proposed to remind user where to check logs for troubleshooting/review
=> Added output where to check logs after script runs
